### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by gxg2002cn** [JiekaiLab/SOT#4]
![image](https://user-images.githubusercontent.com/37469970/52863737-e582e080-3138-11e9-8164-206236ce3607.png)
Hi Lihui,
I met an error when installing SOT by using windows system, R3.5.1. I wonder if you can give me any suggestion to solve the problem. Thank you very much!

> devtools::install_github("JiekaiLab/SOT")
Error in read.dcf(path) : 
  Found continuation line starting '    apcluster, ...' at begin of record.

**Comment by charliex210** [comment]
Hi,
I think there is something wrong with ident. I have fixed it and you can try to install again.

**Comment by gxg2002cn** [comment]
Hi Charlie,
Thanks a lot for your great efforts. SOT running in my computer now.
Best,
Xiaogang
