### ISSUE TITLE
how to determine the k value in function layout_2d

### ISSUE THREAD

**Issue by lixin4306ren** [JiekaiLab/SOT#5]
Hi, I tired layout_2d with different k values to visualize the results. However, the topologies with different k values varied a lot, which one should I use and how about other parameters? Thanks.

**Comment by charliex210** [comment]
Hi lixin,
To my knowledge, there is no absolute standard to set the k value. Empirically, we often set k≈sqrt(n) where n is the sample size. As you see, force directed layout would vary a lot based on the k and random seed you chose. You can try another visualized method to get a more stable result, e.g. umap. Set `layout_method = "FR"` in function `layout_2d`. Some parameters can be modified to optimize the visualization, see `?layout_2d`.
Thanks.
