### ISSUE TITLE
Error message: worker initialization failed: there is no package called ‘irlba’

### ISSUE THREAD

**Issue by genecell** [JiekaiLab/SOT#8]
Hi,

When I run ap.cluster function, I got the error message:
`Error in e$fun(obj, substitute(ex), parent.frame(), e$data) : 
  worker initialization failed: there is no package called ‘irlba’’`
But I did install and import the irlba package.

Thanks in advance!
MD

**Comment by charliex210** [comment]
Hi, 
Thank you for your interest in SOT! I think the problem could be caused by the parallel programme. What are the versions of your `doParallel` and `foreach` packages? 
In another way, you can set the `ncore=1` in `ap.cluster` and `reduce.cluster` to avoid parallel computing. 
Best
Lihui

**Comment by genecell** [comment]
Hi Lihui,

Thank you for your rapid reply!
It works now after I set the `ncore=1` in `ap.cluster` and `reduce.cluster`.
The versions of `doParallel` and `foreach` packages are 1.0.14 and 1.4.4 respectively.
Could you please briefly explain why it broke down in parallel computing? Thanks!

Best regards,
MD

**Comment by charliex210** [comment]
Hi,
I have checked the code in Linux and Windows and it works well. I am not sure why it broke down in your system. Could you please use `sessionInfo()` and paste the results for me?  I will try to reproduce the error.
Best
Lihui
